### ISSUE TITLE
Set tasks status to complete or incomplete by changing its checkbox state

### ISSUE THREAD

**Issue by marbetschar** [elementary/tasks#45]
What the title says.

**Comment by marbetschar** [comment]
Made a first attempt but toggling the state by using the `CheckButton`'s signal and executing `component.set_status` throws a `SegmentationFault`. Any idea why?

The code in question is in the toggle-state branch and does the following:

```
...
construct {
  completed = component.get_status () == ICal.PropertyStatus.COMPLETED;

  var check = new Gtk.CheckButton ();
  check.active = completed;
  check.toggled.connect (() => {
    completed = check.active;

    // this throws a Segmentation fault. Why?
    component.set_status(completed ? ICal.PropertyStatus.COMPLETED : ICal.PropertyStatus.NONE);
  });
...
```

**Comment by marbetschar** [comment]
**UPDATE**: Obviously the previous code was trying to set the wrong status. This is fixed now in the `toggle-state` branch. However, there is still a `SegmentationFault`. It seems to always occur when we try to set `ICal.PropertyStatus.NONE`.

Any ideas anyone?

**Comment by marbetschar** [comment]
@danrabbit checked the [`CalendarModel`](https://github.com/elementary/calendar/blob/master/core/Model/CalendarModel.vala) and tried to adapt. For some reason the `SegmentationFault` seems to be gone - no idea why.

But the `ICal.Component` does seem to loose it's data when I pass it through a Signal for saving. Therefore the `ECal.Client` fails to save, claiming it can't find any matching entity. Any idea what's wrong?

The code in question is located here:
https://github.com/elementary/tasks/blob/toggle-state/src/Widgets/TaskRow.vala#L38

**Comment by marbetschar** [comment]
It should be possible to toggle the task status by:

- [ ] Click the checkbox
- [ ] Select the task row and hit SPACE

**Comment by marbetschar** [comment]
@danrabbit or @tintou any idea why `component.get_uid ()` is empty in `on_component_update` of `ListView`?

Trying to pass the `ICal.Component` for updating like this:
1. [Firing `TaskRow.component_update` from bind `CheckButton.toggled`](https://github.com/elementary/tasks/blob/133dff3daf3f4818dd0181879d11c169e5914d69/src/Widgets/TaskRow.vala#L44)
    - `component.get_uid ()` is set
2. [Executing `on_component_update` in `ListView` from bind `TaskRow.component_update`](https://github.com/elementary/tasks/blob/133dff3daf3f4818dd0181879d11c169e5914d69/src/ListView.vala#L122)
    - `component.get_uid ()` is **NOT** set

**Comment by marbetschar** [comment]
@tintou here's the gdb backtrace - any idea why the tasks app crashes as soon as we try to [update an `ICal.Component` here](https://github.com/elementary/tasks/blob/133dff3daf3f4818dd0181879d11c169e5914d69/src/ListView.vala#L143) when [the checkbox state is toggled](https://github.com/elementary/tasks/blob/133dff3daf3f4818dd0181879d11c169e5914d69/src/Widgets/TaskRow.vala#L48)?

```
(gdb) backtrace
#0  0x00007ffff5eefe30 in pvl_head () at /usr/lib/x86_64-linux-gnu/libical.so.3
#1  0x00007ffff5ed92d9 in icalcomponent_get_first_property () at /usr/lib/x86_64-linux-gnu/libical.so.3
#2  0x00007ffff5edb330 in icalcomponent_get_uid () at /usr/lib/x86_64-linux-gnu/libical.so.3
#3  0x00005555555624b7 in _tasks_task_row___lambda5_ (_data7_=0x55555596a440) at /home/marbetschar/Development/tasks/src/Widgets/TaskRow.vala:45
#4  0x000055555556261e in __tasks_task_row___lambda5__gtk_toggle_button_toggled (_sender=0x555555d91780 [GtkCheckButton], self=0x55555596a440)
    at /home/marbetschar/Development/tasks/src/Widgets/TaskRow.vala:44
#8  0x00007ffff789612f in <emit signal ??? on instance 0x555555d91780 [GtkCheckButton]> (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../../gobject/gsignal.c:3447
    #5  0x00007ffff787a10d in g_closure_invoke (closure=0x555555c47580, return_value=0x0, n_param_values=1, param_values=0x7fffffffc0a0, invocation_hint=0x7fffffffc020) at ../../../../gobject/gclosure.c:804
    #6  0x00007ffff788d05e in signal_emit_unlocked_R (node=node@entry=0x5555558cb0e0, detail=detail@entry=0, instance=instance@entry=0x555555d91780, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffc0a0) at ../../../../gobject/gsignal.c:3635
    #7  0x00007ffff7895715 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffc260) at ../../../../gobject/gsignal.c:3391
#9  0x00007ffff699e0dd in gtk_toggle_button_clicked (button=0x555555d91780 [GtkCheckButton]) at ../../../../gtk/gtktogglebutton.c:612
#10 0x00007ffff787a346 in _g_closure_invoke_va (closure=0x55555586def0, return_value=0x0, instance=0x555555d91780, args=0x7fffffffc570, n_params=0, param_types=0x0) at ../../../../gobject/gclosure.c:867
#11 0x00007ffff78959ff in g_signal_emit_valist (instance=0x555555d91780, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffc570) at ../../../../gobject/gsignal.c:3300
#12 0x00007ffff789612f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../../gobject/gsignal.c:3447
#13 0x00007ffff67a4add in gtk_button_do_release (button=0x555555d91780 [GtkCheckButton], emit_clicked=<optimized out>) at ../../../../gtk/gtkbutton.c:1843
#14 0x00007ffff67a4b35 in gtk_real_button_released (button=0x555555d91780 [GtkCheckButton]) at ../../../../gtk/gtkbutton.c:1961
#18 0x00007ffff789612f in <emit signal ??? on instance 0x555555d91780 [GtkCheckButton]> (instance=instance@entry=0x555555d91780, signal_id=<optimized out>, detail=detail@entry=0) at ../../../../gobject/gsignal.c:3447
    #15 0x00007ffff787a10d in g_closure_invoke (closure=0x55555589f460, return_value=0x0, n_param_values=1, param_values=0x7fffffffc870, invocation_hint=0x7fffffffc7f0) at ../../../../gobject/gclosure.c:804
    #16 0x00007ffff788d12e in signal_emit_unlocked_R (node=node@entry=0x555555894840, detail=detail@entry=0, instance=instance@entry=0x555555d91780, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffc870) at ../../../../gobject/gsignal.c:3565
    #17 0x00007ffff7895715 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffca30) at ../../../../gobject/gsignal.c:3391
#19 0x00007ffff67a2f90 in multipress_released_cb (gesture=0x555555b282c0 [GtkGestureMultiPress], n_press=<optimized out>, x=<optimized out>, y=<optimized out>, widget=0x555555d91780 [GtkCheckButton]) at ../../../../gtk/gtkbutton.c:666
#20 0x00007ffff514fdae in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#21 0x00007ffff514f71f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#22 0x00007ffff787aced in g_cclosure_marshal_generic_va (closure=0x555555c47050, return_value=0x0, instance=<optimized out>, args_list=<optimized out>, marshal_data=<optimized out>, n_params=3, param_types=0x55555594c380) at ../../../../gobject/gclosure.c:1604
#23 0x00007ffff787a346 in _g_closure_invoke_va (closure=0x555555c47050, return_value=0x0, instance=0x555555b282c0, args=0x7fffffffd030, n_params=3, param_types=0x55555594c380) at ../../../../gobject/gclosure.c:867
#24 0x00007ffff78959ff in g_signal_emit_valist (instance=0x555555b282c0, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd030) at ../../../../gobject/gsignal.c:3300
```
