### ISSUE TITLE
Tasks cannot be unchecked

### ISSUE THREAD

**Issue by danrabbit** [elementary/tasks#71]
Once checked, a task cannot be unchecked. It will revert to being checked after a couple seconds

**Comment by marbetschar** [comment]
Works for me in current master against Nextcloud. Do you still encounter this issue?

**Comment by danrabbit** [comment]
Yeah still having this issue with Gtasks

**Comment by danrabbit** [comment]
Now we're getting a crash, which I suppose is progress :)

Got this backtrace:

```
#0  0x00007ffff5eebf35 in pvl_data () at /usr/lib/x86_64-linux-gnu/libical.so.3
#1  0x00007ffff5ed4f67 in  () at /usr/lib/x86_64-linux-gnu/libical.so.3
#2  0x00007ffff5ed7330 in icalcomponent_get_uid () at /usr/lib/x86_64-linux-gnu/libical.so.3
#3  0x000055555555fec2 in __lambda26_ (_data5_=0x55555594fea0, obj=0x555555afc160, results=0x555555e27000)
    at /home/daniel/Projects/tasks/src/ListView.vala:320
#4  0x0000555555560199 in ___lambda26__gasync_ready_callback (source_object=0x555555afc160, res=0x555555e27000, self=0x55555594fea0)
    at /home/daniel/Projects/tasks/src/ListView.vala:315
#5  0x00007ffff6ff6136 in g_simple_async_result_complete () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007ffff6ff61d9 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007ffff7b0a285 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff7b0a650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff7b0a6dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff701de3d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x000055555555d43d in tasks_application_main (args=0x7fffffffde78, args_length1=1) at /home/daniel/Projects/tasks/src/Application.vala:101
#12 0x000055555555d480 in main (argc=1, argv=0x7fffffffde78) at /home/daniel/Projects/tasks/src/Application.vala:99
```

**Comment by marbetschar** [comment]
@danrabbit can you please check if #104 fixes this issue? My best guess as of now would be that you are trying to update a task while another update of the same task is not completed yet.

Thanks to the new activity indicator you should be able to verify this (there might be further actions needed to avoid mutating a task while a save is in progress).

**Comment by danrabbit** [comment]
This seems to be resolved in Master
